trigger:
  branches:
    include:
      - main # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x' # Use the Node.js version your React app requires
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install Dependencies and Build'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'build'
      artifactName: 'react-app-build'
      publishLocation: 'pipeline'
